# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ajA54I1yi17eFQpT_rGBN3epCCY0mGlu
"""

import pandas as pd
import numpy as np

df=pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user',sep="|")

df

# First 10elements
df.head(10)

# Last 10 elements are
df.tail(10)

# Number of observations in the data
df.shape[0]

# Number cf columns
df.shape[1]

# all the columns
df.columns

# How the dataset indexed
ind=df.index.tolist()
print(",".join(str(num) for num in ind))

# To know the datatype of the dataset
df.info()

# print only occupation column
df['occupation']

# How many different occupations are therein the dataset
df['occupation'].nunique()

# what is the most frequent occupation
m=df['occupation'].value_counts()
m.index[0]

# dataframe informatio
df.info()

#Describe all columns
[df[var].describe() for var in df.columns]

# summarize only occupation column
df['occupation'].value_counts()

# what is the mean age of the user
df.columns
df['age'].mean()

# age of the least accurance
mad=df['age'].sort_values().min()
mad

